/** @format */

export const Menu = [
	{
		id: 1,
		name: 'Masala Dosa',
		category: 'South Indian',
		image: 'images/food(19).jpg',
		price: 50,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 2,
		name: 'Idli',
		category: 'South Indian',
		image: 'images/food(20).jpg',
		price: 35,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 3,
		name: 'Sambhar Bada',
		category: 'South Indian',
		image: 'images/food(14).jpg',
		price: 40,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 4,
		name: 'Uttpam',
		category: 'South Indian',
		image: 'images/food(12).jpg',
		price: 80,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 5,
		name: 'Noddles',
		category: 'Chinese',
		image: 'images/food(8).jpg',
		price: 40,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 6,
		name: 'Kothe',
		category: 'Chinese',
		image: 'images/food(5).jpg',
		price: 80,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 7,
		name: 'Chrispy corn',
		category: 'Chinese',
		image: 'images/food(2).jpg',
		price: 75,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 8,
		name: 'Manchurian',
		category: 'Chinese',
		image: 'images/food(6).jpg',
		price: 40,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 9,
		name: 'Veg Sandwich',
		category: 'Sandwiches',
		image: 'images/food(13).jpg',
		price: 40,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 10,
		name: 'Masala Sandwich',
		category: 'Sandwiches',
		image: 'images/food(7).jpg',
		price: 45,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 11,
		name: 'Bombay Sandwich',
		category: 'Sandwiches',
		image: 'images/food(15).jpg',
		price: 50,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 12,
		name: 'Grilled Sandwich',
		category: 'Sandwiches',
		image: 'images/food(3).jpg',
		price: 60,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 13,
		name: 'Cold Coffee',
		category: 'Shakes And coffee',
		image: 'images/food(18).jpg',
		price: 60,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 14,
		name: 'Hot Coffee',
		category: 'Shakes And coffee',
		image: 'images/food(4).jpg',
		price: 30,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 15,
		name: 'Oreo Shake',
		category: 'Shakes And coffee',
		image: 'images/food(9).jpg',
		price: 80,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 16,
		name: 'Banana Shake',
		category: 'Shakes And coffee',
		image: 'images/food(1).jpg',
		price: 50,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 17,
		name: 'Chole Bhature',
		category: 'North Indian',
		image: 'images/food(16).jpg',
		price: 100,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 18,
		name: 'Panner kulche',
		category: 'North Indian',
		image: 'images/food(10).jpg',
		price: 120,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 19,
		name: 'Chole kulche',
		category: 'North Indian',
		image: 'images/food(20).jpg',
		price: 140,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 20,
		name: 'Panner Butter Naan',
		category: 'North Indian',
		image: 'images/food(11).jpg',
		price: 160,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 21,
		name: 'Red Pasta',
		category: 'Pasta',
		image: 'images/food(21).jpg',
		price: 80,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
	{
		id: 22,
		name: 'White Pasta',
		category: 'Pasta',
		image: 'images/food(22).jpg',
		price: 100,
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
	},
]
